debug: true

logging:
  path: var/log/test.log
  file:
    max-size: 10000KB
    max-history: 1
  level:
    root: TRACE
    org:
      springframework:
        web: OFF
      hibernate: OFF
      apache:
          tomcat: OFF
spring:
  output:
    ansi:
      enabled: DETECT