# 如果是默认的资源方式，因为页面跳转使用“Forwarding”方式，所以需要ModeAndView的路径使用此前缀，
# 但如果使用模板引擎，FreeMarker，则是直接读取资源中的path的文件，所以不需要此内容
static-path-pattern: /static/

spring:
  mvc:
    # 将所有的资源都采用同样的访问路径前缀 TODO 部分目录权限的处理，不能没有权限的访问到
    static-path-pattern: ${static-path-pattern}**
  resources:
    chain:
      strategy:
        content:
          # 浏览器缓存解决方案，采用 采用 content生成一个hash值，加入到文件访问路径中，
          # 采用自定模板宏的方式。参照“ResourceUrlProviderController”
          # path 是去除，系统的资源路径之后的路径进行匹配的，如：“/static/jquery/3.4.1/jquery.js” hash 的字符串是 “/jquery/3.4.1/jquery.js”，其中的"/static"是系统资源路径
          paths: /**
          enabled: true
    # 采用覆盖的方式
    static-locations:
      # 系统默认
      - classpath:/META-INF/resources/
      - classpath:/resources/
      - classpath:/static/
      - classpath:/public/
      # 自定义 资源路径
      - classpath:/myresources/
